### ISSUE TITLE
node-gyp issue in node scripts/install.js 

### ISSUE THREAD

**Issue by lucylow** [lucylow/Mrs.Robot#4]
> yarn add @tensorflow/tfjs-node-gpu

error:
* Building TensorFlow Node.js bindings
/Users/lucylow/Desktop/Mrs.Robot/fashion-mnist-vae/node_modules/@tensorflow/tfjs-node/scripts/install.js:157
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda/bin/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack Could not find platform independent libraries <prefix>
gyp ERR! stack Could not find platform dependent libraries <exec_prefix>
gyp ERR! stack Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
gyp ERR! stack ImportError: No module named site
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lucylow/Desktop/Mrs.Robot/fashion-mnist-vae/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at cp.exec (/Users/lucylow/Desktop/Mrs.Robot/fashion-mnist-vae/node_modules/@tensorflow/tfjs-node/scripts/install.js:157:13)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)

**Comment by lucylow** [comment]
set python home environments 

> export PYTHONHOME=/usr/local
